---
provider:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  auth_pass: "{{ ansible_ssh_pass }}"
  password: "{{ ansible_ssh_pass }}"
  timeout: 120
enable_secret: C1sco123
local_auth_accounts:
  - username: admin
    password: admin
    privilege_level: 15