---
all:
  vars:
    username: admin
    password: "123"
    ansible_connection: local
    ansible_python-interpreter: "usr/bin/env python3"
  children:
    sjc:
      hosts:
        PE1:
          ansible_host: 10.10.0.15
        PE2:
          ansible_host: 10.10.0.16
    sjc1:
      hosts:
        PE3:
          ansible_host: 10.10.0.17
        PE4:
          ansible_host: 10.10.0.18      

    pedgeL:
      hosts:
        PE1:
          ansible_host: 10.10.0.15
    pedgeR:
      hosts:
        PE2:
          ansible_host: 10.10.0.16
    pedgeB:
          hosts:
            PE3:
              ansible_host: 10.10.0.17
    pedgeT:
      hosts:
        PE4:
          ansible_host: 10.10.0.18
      