---
- name: Provision L2VPN Eth-Eth For PE4
  gather_facts: no
  hosts: pedgeR
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 180

    vcid: 100
    int_forw: GigabitEthernet2/0 
    encapsulation: mpls
    ip_add: 10.255.255.13


  tasks:
    - name: Create configurations L2VPN Ethernet-Ethernet
      ios_config:
        provider: "{{ credentials }}"
        authorize: yes
        lines:
          - xconnect {{ ip_add }} {{ vcid }} encapsulation {{ encapsulation }}
          - no shutdown
        parents: ['interface {{ int_forw }}']
        match: exact

