---
- name: L2VPN routing PE-CE PROCEDURE 
  hosts: sjc
  connection: local
  gather_facts: no
  vars:
    switch_role: "distribution"
    ansible_connection: netconf
    ansible_network_os: ios

  roles:
  - eigrp
  - ospf