---
- name: ACCESS PROCEDURE 1
  hosts: pedgeL
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:
    - ios_facts:
        provider: "{{ credentials }}"
      name: Collect IOS facts
      register: ios_facts
    - ios_facts:
        provider: "{{ credentials }}"
      name: run the module netconf
      netconf_config:
        backup: yes
      register: ios_facts

    - debug:
        msg: "{{ ansible_net_hostname }}, version: {{ ansible_net_version }}"