---
- name: ACCESS PROCEDURE 1
  hosts: pedgeL
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:
    - name: Remove GigabitEthernet4 IPv4 and IPv6 address
      ios_l3_interface:
        provider: "{{ credentials }}"
        name: GigabitEthernet4
        state: absent
    - name: Set GigabitEthernet4 Pv4 address
      ios_l3_interface:
        provider: "{{ credentials }}"
        name: GigabitEthernet4
        ipv4: 192.168.0.1/24
    - name: lock candidate netconf 
      netconf_config:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        content: |
            <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
                <system xmlns="urn:ietf:params:xml:ns:yang:ietf-system">
                    <ntp>
                        <enabled>false</enabled>
                        <server operation="remove">
                            <name>ntp1</name>
                        </server>
                    </ntp>
                </system>
            </config>
             
       
     
