---
- name: TEST PROCEDURE 
  hosts: provid1
  connection: local
  gather_facts: no
  vars:
    switch_role: "distribution"
    ansible_connection: netconf
    ansible_network_os: ios

  roles:
  - ip_addressing
  - mpls
  - routing_core