---
- name: ACCESS PROCEDURE 1
  hosts: pedgeL
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:
    - name: Remove GigabitEthernet0/3 IPv4 and IPv6 address
      ios_l3_interface:
        provider: "{{ credentials }}"
        name: GigabitEthernet4
        state: absent
    - name: Set GigabitEthernet0/3 IPv4 address
      ios_l3_interface:
        provider: "{{ credentials }}"
        name: GigabitEthernet4
        ipv4: 192.168.0.1/24
