---
- name: TEST PROCEDURE 
  hosts: sjc
  connection: local
  gather_facts: no
  vars:
    switch_role: "distribution"
    ansible_connection: network_cli
    ansible_network_os: ios
  roles:
    - hostname
    