---
- name: ACCESS PROCEDURE 1
  hosts: sjc
  connection: local
  gather_facts: no
  vars:
    provider_role: "vrf"
  tasks:
    - name: run the new module
      my_test:
        name: 'hello'
        new: true


