---
- name: TEST PROCEDURE 
  hosts: sjc
  connection: local
  vars:
    switch_role: "distribution"
    ansible_connection: netconf
    ansible_network_os: ios
  task:
  - name: ok
    netconf_config:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      auth_pass: "{{ ansible_ssh_pass }}"
  roles:
    - hostname
    