---
- name: Collect facts
  gather_facts: no
  hosts: pedge
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:

    - debug:
        msg: "{{ ansible_net_hostname }}, version: {{ ansible_net_version }}"

