---
all:
  vars:
    username: admin
    password: admin
    ansible_connection: local
    ansible_python-interpreter: "usr/bin/env python"
  children:
    sjc:
      hosts:
        PE1:
          ansible_host: 10.10.0.15
        PE2:
          ansible_host: 10.10.0.16

    pedgeL:
      hosts:
        PE3:
          ansible_host: 10.10.0.17
    pedgeR:
      hosts:
        PE4:
          ansible_host: 10.10.0.18

  