---
- name: ACCESS PROCEDURE 1
  hosts: sjc
  connection: local
  gather_facts: no
  vars:
    provider_role: "vrf"
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30
  tasks:
    - name: Remove GigabitEthernet0/4 IPv4 and IPv6 address
      ios_l3_interface:
        provider: "{{ credentials }}"
        name: GigabitEthernet0/4
        state: absent
    - name: Set GigabitEthernet0/4 Pv4 address
      ios_l3_interface:
        provider: "{{ credentials }}"
        name: GigabitEthernet0/4
        ipv4: 192.168.0.1/24
    - name: run the new module
      netconf_config:
        provider: "{{ credentials }}"
        name: 'hello'
        new: true
      register: testout