---
- name: ACCESS PROCEDURE 1
  hosts: sjc
  connection: local
  gather_facts: no
  vars:
    provider_role: "vrf"
  tasks:
  - name: run the new module
    modtest:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30
      name: 'hello'
      new: true
    register: testou
  - name: dump test output
    debug:
      msg: '{{ testout }}'