---
- name: ACCESS PROCEDURE 1
  hosts: sjc
  connection: local
  gather_facts: no
  vars:
    provider_role: "vrf"
  tasks:
    - name: run the new module
      modtest:
        name: 'hello'
        new: true
      register: testout
    - name: dump test output
      debug:
        msg: '{{ testout }}'
    - name: lock candidate netconf 
      netconf_config:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        timeout: 30
        backup: yes
      register: backup_junos_location