---
- name: ACCESS PROCEDURE 1
  hosts: sjc
  connection: local
  gather_facts: no
  vars:
    provider_role: "vrf"
  tasks:
    - debug:
        msg: "before we run our role"
    - import_role:
        name: vrf
    - debug:
        msg: "after we ran our role"