---
- name: ping example playbook
  hosts: P1

  tasks:
    - name: test ping
      ping:
    - name: run show version on remote devices
      ios_command:
        commands:
         - show memory statistics
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"