---
- name: ping example playbook
  hosts: P1
  vars:
      credentials:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        timeout: 30
  tasks:
   - name: test ping
     ping: