- name: BUILD EIGRP XML DATA
  template:
    src: eigrp.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/eigrp.xml"
    
# - name: BUILD EIGRP NSF CLI DATA
#   template:
#     src: nsf.j2
#     dest: "{{ configs_dir }}/{{ inventory_hostname }}/eigrp_nsf.cfg"
# 
# - name: PUSH CONFIG TO REMOTES
#   ios_config:
#     provider: "{{ provider }}"
#     src: "{{ configs_dir }}/{{ inventory_hostname }}/eigrp.cfg"