- name: BUILD EIGRP XML DATA
  template:
    src: eigrp.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/eigrp.xml"
    when: ansible_network_os == 'ios'
- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/eigrp.xml"
    when: ansible_network_os == 'ios'