---
interfaces:
  - type: FastEthernet
    name: 0/1
    description: connected to P2
    ipv4: 10.255.254.13
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: FastEthernet
    name: 0/2
    description: connected to P4
    ipv4: 10.255.254.33
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: FastEthernet
    name: 0/3
    description: connected to PE2
    ipv4: 10.255.254.29
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true    
  - type: Loopback
    name: 0
    description: Loopback0
    ipv4: 10.255.255.3
    ipv4_mask: 255.255.255.255
    enabled: true
