---
interfaces:
  - type: FastEthernet
    name: 0/1
    description: connected to P1
    ipv4: 10.255.254.6
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: FastEthernet
    name: 0/2
    description: connected to P3
    ipv4: 10.255.254.34
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true
  - type: FastEthernet
    name: 0/3
    description: connected to PE4
    ipv4: 10.255.254.41
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: true    
  - type: Loopback
    name: 0
    description: Loopback0
    ipv4: 10.255.255.4
    ipv4_mask: 255.255.255.255
    enabled: true
