---
interfaces:
  - name: GigabitEthernet1
    description: 
    ipv4: 10.10.0.15
    ipv4_mask: 255.255.255.0
    enabled: no shutdown
  - name: GigabitEthernet2
    description: connected to P1
    ipv4: 10.255.254.10
    ipv4_mask: 255.255.255.252
    mpls: mpls ip
    enabled: no shutdown
  - name: GigabitEthernet3
    description: connected to P2
    ipv4: 10.255.254.18
    ipv4_mask: 255.255.255.252
    mpls: mpls ip
    enabled: no shutdown
  - name: GigabitEthernet4
    description: connected to customer ONE
    vrf: ONE
    ipv4: 10.255.20.1
    ipv4_mask: 255.255.255.0
    enabled: no shutdown
  - name: GigabitEthernet5
    description: connected to customer TWO
    vrf: TWO
    ipv4: 10.255.20.1
    ipv4_mask: 255.255.255.252
    enabled: no shutdown     
  - name: Loopback0
    description: Loopback0
    ipv4: 10.255.255.11
    ipv4_mask: 255.255.255.255
    enabled: no shutdown  


vrf:
  - definitions:
    name: A
    rd: 10.255.255.40:1
    target-export: 10.255.255.40:1
    target-import: 10.255.255.41:1
  - definitions:
    name: B
    rd: 10.255.255.50:2
    target-export: 10.255.255.50:2
    target-import: 10.255.255.51:2
