---
interfaces:
  - name: GigabitEthernet1
    description: 
    ipv4: 10.10.0.15
    ipv4_mask: 255.255.255.0
    enabled: no shutdown
  - name: GigabitEthernet2
    description: connected to P1
    ipv4: 10.255.254.10
    ipv4_mask: 255.255.255.252
    mpls: mpls ip
    enabled: no shutdown
  - name: GigabitEthernet3
    description: connected to P2
    ipv4: 10.255.254.18
    ipv4_mask: 255.255.255.252
    mpls: mpls ip
    enabled: no shutdown
  - name: GigabitEthernet4
    description: connected to customer ONE
    vrf: ONE
    ipv4: 10.255.20.1
    ipv4_mask: 255.255.255.0
    enabled: no shutdown
  - name: GigabitEthernet5
    description: connected to customer TWO
    vrf: TWO
    ipv4: 10.255.20.1
    ipv4_mask: 255.255.255.252
    enabled: no shutdown     
  - name: Loopback0
    description: Loopback0
    ipv4: 10.255.255.11
    ipv4_mask: 255.255.255.255
    enabled: no shutdown  


vrfs:
  - name: ONE
    rd: 10.255.255.20:1
    target-export: 10.255.255.21:1
    target-import: 10.255.255.20:1
  - name: TWO
    rd: 10.255.255.30:2
    target-export: 10.255.255.31:2
    target-import: 10.255.255.30:2



interface_fors:
  - name: 4
    forwarding: ONE
    ipadd: 10.255.10.1
    mask: 255.255.255.252
    enabled: true
  - name: 5
    forwarding: TWO
    ipadd: 10.255.20.1
    mask: 255.255.255.252


ospfs:
  - id: 2
    vrf: ONE
    bgp-as: 64512
    network: 10.255.11.0
    mask: 0.0.0.3
    area: 2    


eigrps:
  - id: 200
    vrf: TWO
    eigrp-as: 200
    bgp-as: 64512
    network: 10.255.20.0
    mask: 0.0.0.3


neighbors_bgp:
  - id: 10.255.255.12
    as: 64512
    loopback: 0
  - id: 10.255.255.13
    as: 64512
    loopback: 0
  - id: 10.255.255.14
    as: 64512
    loopback: 0

customers:
  - name: ONE
    redistribute: ospf
    ospf-id: 2
  - name: TWO
    redistribute: eigrp
    ospf-id: 200