---
interfaces:
  - GigabitEthernet:
    name: 1
    description: 
    ipv4: 10.10.0.15
    ipv4_mask: 255.255.255.0
    enabled: no shutdown
  - GigabitEthernet:
    name: 2
    description: connected to P1
    ipv4: 10.255.254.10
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: no shutdown
  - GigabitEthernet:
    name: 3
    description: connected to P2
    ipv4: 10.255.254.18
    ipv4_mask: 255.255.255.252
    mpls: true
    enabled: no shutdown
  - GigabitEthernet:
    name: 4
    description: connected to customer ONE
    vrf: ONE
    ipv4: 10.255.20.1
    ipv4_mask: 255.255.255.0
    enabled: no shutdown
  - GigabitEthernet:
    name: 5
    description: connected to customer TWO
    vrf: TWO
    ipv4: 10.255.20.1
    ipv4_mask: 255.255.255.252
    enabled: no shutdown     
  - Loopback:
    name: 0
    description: Loopback0
    ipv4: 10.255.255.11
    ipv4_mask: 255.255.255.255
    enabled: no shutdown  


neighbors_bgp:
  - id: 10.255.255.11
    as: 64512
    loopback: 0
  - id: 10.255.255.12
    as: 64512
    loopback: 0
  - id: 10.255.255.14
    as: 64512
    loopback: 0

routing-core:
  - name: ospf
    id: 1
    router-id: 10.255.255.13
  - network: 
    ip: 10.255.254.24
    mask: 0.0.0.3
    area: 0
  - network: 
    ip: 10.255.255.13
    mask: 0.0.0.3
    area: 0

pseudowire:
  name: ETH-TO-ETH
  encapsulation: mpls
  interface: 3
  ip-address: 10.255.255.14
  vcid: 34