---
- name: Collect facts
  gather_facts: no
  hosts: sjc
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:
    - ios_facts:
        provider: "{{ credentials }}"
      name: Collect IOS facts
      register: ios_facts

    - name: example copying file with owner and permissions
      copy:
        content: "{{ ios_facts | to_nice_json }}"
        dest: "/out/{{inventory_hostname}}_foo.json"
        mode: 0644

    - debug:
        msg: "{{ ansible_net_hostname }}, version: {{ ansible_net_version }}"