---
- name: Collect facts
  gather_facts: no
  hosts: sjc
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:
    - ios_facts:
        provider: "{{ credentials }}"
      name: Collect IOS facts
      register: ios_facts
     
    - name: Copy using the 'ios_facts' for inline data
      copy:
        content: "{{ ios_facts | to_nice_json }}"
        dest: "out/{{inventory_hostname}}_ios_facts.json" 

    - debug:
        msg: "{{ ansible_net_hostname }}, version: {{ ansible_net_version }}"