---
- name: Debugging
  hosts: sjc
  tasks:
    - name: Dump all vars
      # action: template src=templates/dumpall.j2 dest=/tmp/ansible.all
      debug: var=hostvars[inventory_hostname]
      msg: "{{ username }}"

    - copy: content="{{ ios_facts | to_nice_json }}" dest="out/{{inventory_hostname}}_ios_facts.json"
      name: Save facts to JSON file

    - debug:
        msg: "{{ test_variable }}"
      tags:
        - debug