---
- name: Provision EIGRP
  gather_facts: no
  hosts: pedgeR
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 180

    bgp_as_number: 64512
    eigrp_as_number: 200
    eigrp_metric: 1
    network_wildcard_mask_3: 0.0.0.3
    autonomous_system_200: 200
    network_prefix_21: 10.255.21.0
    mask_4: 255.255.255.252
    vrf_b: B
    int_forw: GigabitEthernet1/0 
    ip_add: 10.255.21.1


  tasks:
    - name: Create configurations EIGRP
      ios_config:
        provider: "{{ credentials }}"
        authorize: yes
        lines:
          - address-family ipv4 vrf {{ vrf_b }}
          - redistribute bgp {{ bgp_as_number }}
          - network {{ network_prefix_21 }} {{ network_wildcard_mask_3 }}
          - autonomous-system {{ autonomous_system_200 }}
        parents: ['router eigrp  {{ eigrp_as_number }}']
        match: exact

    - name: Create  redistribute Router eigrp on bgp 64512
      ios_config:
        provider: "{{ credentials }}"
        authorize: yes
        lines:
          - address-family ipv4 vrf {{ vrf_b }}
          - redistribute eigrp {{ eigrp_as_number }}
        parents: ['router bgp  {{ bgp_as_number }}']
        match: exact

    - name: Create Forwarding vrf B on interface
      ios_config:
        provider: "{{ credentials }}"
        authorize: yes
        lines:
          - ip vrf forwarding B
          - no shutdown
          - ip address {{ ip_add }} {{mask_4 }}
        parents: ['interface {{ int_forw }}']
        match: exact



