---
all:
  vars:
    username: admin
    password: admin
    ansible_connection: local
    ansible_python-interpreter: "usr/bin/env python"
  children:
    sjc:
      hosts:
        P1:
          ansible_host: 192.168.200.11
        P2:
          ansible_host: 192.168.200.12
        P3:
          ansible_host: 192.168.200.13
        PE1:
          ansible_host: 192.168.200.21
        PE2:
          ansible_host: 192.168.200.22

  