---
all:
  vars:
    username: admin
    password: admin
    ansible_connection: local
  children:
    sjc:
      hosts:
        192.168.200.11:
        192.168.200.12:
        192.168.200.13:
        192.168.200.21:
        192.168.200.22:
  