---
- name: Provision VRF A
  gather_facts: no
  hosts: sjc
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 180

    rd_id: '10.255.255.20:1'
    rt_imp: '10.255.255.20:1'
    rt_exp: '10.255.255.20:1'
    vrf_name: A
    int_name: GigabitEthernet1/0

  tasks:
    - name: Create configurations MP-BGP
      ios_config:
        provider: "{{ credentials }}"
        authorize: yes
        lines:
          - rd {{ rd_id }}
          - route-target export {{ rt_exp }}
          - route-target import {{ rt_imp }}
        parents: ['ip vrf {{ vrf_name }}']
        match: exact

    - name: run show bgp remote devices
      ios_command:
        authorize: yes
        commands:
          - show bgp all
        provider: "{{ credentials }}"
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"    
