---
- name: Provision MP-BGP For PE1
  gather_facts: no
  hosts: pedgeL
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 180

    bgp_as_number: 64512
    ip_loopback: 10.255.255.12
    mask_4: 255.225.255.252


  tasks:
    - name: Create configurations MP-BGP
      ios_config:
        provider: "{{ credentials }}"
        authorize: yes
        lines:
          - neighbor {{ ip_loopback }} remote-as {{ bgp_as_number }}
          - neighbor {{ ip_loopback }} update-source Loopback0
          - address-family ipv4
          - neighbor {{ ip_loopback }} activate
          - exit-address-family
          - address-family vpnv4
          - neighbor {{ ip_loopback }} activate
          - neighbor {{ ip_loopback }} send-community extended
          - exit-address-family
        parents: ['router bgp {{ bgp_as_number }}']
        match: exact

    - name: run show bgp remote devices
      ios_command:
        authorize: yes
        commands:
          - show bgp all
        provider: "{{ credentials }}"
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"    
