---
- name: Provision Network
  gather_facts: no
  hosts: sjc
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:
    - name: Configure VRF For PE1
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_vrf_pe1.j2

    - name: Configure VRF For PE2
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_vrf_pe2.j2

    - name: Configure EIGRP For PE1
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_eigrp_pe1.j2

    - name: Configure EIGRP For PE2
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_eigrp_pe2.j2

    - name: Configure OSPF For PE1
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_ospf_pe1.j2

    - name: Configure OSPF For PE2
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_ospf_pe2.j2
    
    - name: Configure MP-BGP For PE1
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_mp_bgp_pe1.j2    

    - name: Configure MP-BGP For PE2
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_mp_bgp_pe2.j2    

    - name: Configure Redistribution Routes
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_bgp_redistribution-routes.j2   

    - name: Configure L2VPN For PE1
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_l2vpn_p1.j2    

    - name: Configure L2VPN For PE2
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_l2vpn_p2.j2    


