---
- name: Provision Network
  gather_facts: no
  hosts: sjc
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:
    - name: Configure VRF For PE1
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_vrf_pe1.j2
