---
- name: Provision VRF A
  gather_facts: no
  hosts: all
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  #  I decided to enter MPLS VPN variables directly into the Playbook.  There are other options of course
  #  These 5 variables are all that is needed to get a basic VRF enabled, add the RD and RT,
  #  apply the VRF to an interface of choice, and then add the address-family to BGP (could be other protocol)
    rd_id: '10.255.255.20:1'
    rt_imp: '10.255.255.20:1'
    rt_exp: '10.255.255.20:1'
    vrf_name: A
    int_name: GigabitEthernet0/0
    int_ip: '10.255.10.1'

  tasks:
    - name: Create VRF
      ios_config:
        provider: "{{ credentials }}"
        authorize: yes
        lines:
          - rd {{ rd_id }}
          - route-target export {{ rt_exp }}
          - route-target import {{ rt_imp }}
        parents: ['ip vrf {{ vrf_name }}']
        match: exact

    - name: Create and Attach VRF to Interface
      ios_config:
        provider: "{{ credentials }}"
        authorize: yes
        lines:
          - vrf forwarding {{ vrf_name }}
        parents: ['interface {{ int_name }}']
        match: exact

    - name: Configure IP address GigabitEthernet0/0
      ipadm_addr: addr={{ int_ip }} addrobj={{ int_name }} state=up
      
    - name: Run 'show VRF'
      ios_command:
        provider: "{{ credentials }}"
        authorize: yes
        commands:
          - show vrf

    - debug:
        msg: "{{ vrf.a.stdout_lines }}"    
