---
- name: Provision Network
  gather_facts: no
  hosts: sjc
  connection: local
  vars:
    credentials:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:
    - name: Configure EIGRP
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_eigrp.j2
    
    - name: Configure OSPF
      ios_config:
        provider: "{{ credentials }}"
        src: templates/ios_ospf.j2
    
    - name: Configure MP-BGP
      ios_config:
        provider: "{{ credentials }}"
        src: templates/mp_bgp_enter_pe.j2    

