---
- name: Gather facts (Cisco)
  gather_facts: no
  hosts: edgep1
  vars:
    creds:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"

  tasks:
    - ios_facts:
        provider: "{{ creds }}"
      tags: facts_only

    - debug:
        msg: "SN:   {{ ansible_net_serialnum }}"