---
all:
  vars:
    username: admin
    password: admin
    ansible_connection: local
    ansible_python-interpreter: "usr/bin/env python"
  children:
    sjc:
      hosts:
        PE1:
          ansible_host: 192.168.200.21
        PE2:
          ansible_host: 192.168.200.22
    sjc1:
      hosts:
        PE3:
          ansible_host: 192.168.200.23
        PE4:
          ansible_host: 192.168.200.24      

    pedgeL:
      hosts:
        PE1:
          ansible_host: 192.168.200.21
    pedgeR:
      hosts:
        PE2:
          ansible_host: 192.168.200.22
    pedgeB:
          hosts:
            PE2:
              ansible_host: 192.168.200.23
    pedgeT:
      hosts:
        PE2:
          ansible_host: 192.168.200.24
      